import requests

from cfc_challenge.domain.cfc_underwriting import (
    get_external_resources,
    Resource,
    get_hyperlinks,
    get_word_frequency_count,
)


class TestGetResourcesAndLinks:
    response = requests.get("https://www.cfcunderwriting.com/")

    def test_get_external_resources(self):
        external_resources = get_external_resources(self.response)
        assert external_resources == [
            Resource(
                source="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700",
                tag="<link "
                'href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet"/>',
            ),
            Resource(
                source="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css",
                tag="<link "
                'href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" '
                'rel="stylesheet"/>',
            ),
            Resource(
                source="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js",
                tag="<script "
                'crossorigin="anonymous" '
                "integrity="
                '"sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg=="'
                ' src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>',
            ),
            Resource(
                source="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js",
                tag="<script "
                'defer="" '
                'src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js">'
                "</script>",
            ),
            Resource(
                source="https://www.google.com/recaptcha/api.js?render=6LemiyEaAAAAAGwb4nR8oX38fxyM36xjIGbwz6d4",
                tag="<script "
                'src="https://www.google.com/recaptcha/api.js?render=6LemiyEaAAAAAGwb4nR8oX38fxyM36xjIGbwz6d4">'
                "</script>",
            ),
        ]

    def test_get_hyperlinks(self):
        hyperlinks, privacy_policy = get_hyperlinks(self.response)

        assert len(hyperlinks) == 74
        assert privacy_policy == "/en-gb/support/privacy-policy/"


class TestGetWordFrequencyCount:
    privacy_policy = requests.get("https://www.cfcunderwriting.com")

    def test_get_word_frequency_count(self):
        word_frequency_count = get_word_frequency_count(self.privacy_policy)

        assert word_frequency_count == {
            "US": 2,
            "a": 4,
            "about": 2,
            "active": 1,
            "afterward": 1,
            "agreements": 1,
            "ahead": 1,
            "all": 1,
            "always": 1,
            "an": 1,
            "and": 14,
            "announcements": 2,
            "app": 2,
            "are": 4,
            "articles": 2,
            "assailant": 1,
            "assessments": 1,
            "assist": 1,
            "attack": 1,
            "australia": 2,
            "automotive": 1,
            "award": 2,
            "awards": 1,
            "awardwinning": 2,
            "bar": 1,
            "be": 1,
            "best": 2,
            "beverage": 1,
            "both": 1,
            "bring": 1,
            "bringing": 1,
            "broker": 2,
            "business": 3,
            "businesses": 1,
            "by": 3,
            "calculate": 1,
            "calculator": 1,
            "canada": 3,
            "care": 1,
            "careers": 4,
            "case": 2,
            "casualty": 2,
            "cfc": 8,
            "cfcs": 3,
            "challenger": 1,
            "changing": 1,
            "claim": 2,
            "claims": 3,
            "class": 2,
            "clearly": 1,
            "commitment": 1,
            "companies": 1,
            "company": 4,
            "complaints": 1,
            "construction": 2,
            "consumer": 1,
            "contact": 4,
            "continue": 1,
            "corporate": 1,
            "cost": 1,
            "cover": 1,
            "coverage": 1,
            "creating": 2,
            "customer": 2,
            "customers": 1,
            "cuttingedge": 1,
            "cyber": 20,
            "defense": 1,
            "delivers": 1,
            "dentists": 1,
            "devices": 1,
            "digital": 2,
            "directors": 1,
            "discussions": 1,
            "disrupting": 1,
            "do": 1,
            "doctors": 1,
            "document": 1,
            "dont": 1,
            "down": 1,
            "download": 1,
            "during": 1,
            "ehealth": 3,
            "emerging": 1,
            "engineers": 1,
            "enterprise": 1,
            "entertainment": 2,
            "environmental": 2,
            "esg": 1,
            "europe": 1,
            "events": 2,
            "every": 1,
            "everything": 1,
            "excellence": 1,
            "excellent": 2,
            "excess": 3,
            "exposure": 1,
            "face": 1,
            "fair": 1,
            "fast": 1,
            "featured": 2,
            "financial": 2,
            "find": 2,
            "fintech": 3,
            "first": 1,
            "food": 1,
            "for": 10,
            "from": 2,
            "future": 2,
            "fvas": 1,
            "gap": 1,
            "gender": 1,
            "general": 2,
            "get": 1,
            "goods": 1,
            "governance": 3,
            "guidance": 2,
            "guides": 3,
            "has": 1,
            "have": 1,
            "healthcare": 10,
            "helpful": 1,
            "how": 1,
            "in": 4,
            "incident": 1,
            "incredibly": 1,
            "indemnity": 1,
            "industries": 2,
            "industry": 3,
            "information": 2,
            "infringement": 1,
            "innovative": 4,
            "inperson": 1,
            "insights": 1,
            "institutions": 2,
            "insurance": 23,
            "intellectual": 1,
            "investment": 1,
            "is": 2,
            "it": 2,
            "join": 1,
            "just": 1,
            "keen": 1,
            "kidnap": 3,
            "knowledge": 1,
            "knowledgeable": 1,
            "large": 1,
            "latest": 2,
            "lawyer": 1,
            "leadership": 1,
            "learn": 4,
            "liability": 14,
            "licensing": 1,
            "life": 2,
            "made": 1,
            "malpractice": 2,
            "management": 2,
            "managers": 1,
            "manufacturers": 2,
            "manufacturing": 3,
            "marine": 1,
            "market": 1,
            "marketleaders": 1,
            "media": 4,
            "medical": 3,
            "meet": 2,
            "mobile": 1,
            "modern": 1,
            "more": 3,
            "names": 1,
            "new": 3,
            "news": 4,
            "nonprofits": 1,
            "notify": 2,
            "now": 1,
            "of": 6,
            "offerings": 1,
            "officers": 1,
            "one": 2,
            "online": 1,
            "open": 1,
            "or": 2,
            "our": 12,
            "out": 1,
            "outdone": 1,
            "pay": 1,
            "person": 1,
            "pioneers": 1,
            "piracy": 1,
            "platform": 1,
            "platforms": 1,
            "policies": 1,
            "policy": 1,
            "pollution": 1,
            "popular": 1,
            "practices": 1,
            "pragmatic": 1,
            "privacy": 1,
            "private": 1,
            "procedure": 1,
            "product": 6,
            "products": 9,
            "professional": 10,
            "professionals": 3,
            "property": 4,
            "provided": 1,
            "provider": 1,
            "providers": 1,
            "pursuit": 1,
            "ransom": 3,
            "ransomware": 1,
            "rd": 1,
            "ready": 1,
            "real": 1,
            "reassuring": 1,
            "recall": 2,
            "recognition": 1,
            "recovery": 1,
            "recruitment": 2,
            "regulatory": 1,
            "report": 3,
            "representation": 1,
            "resources": 2,
            "response": 3,
            "responsibility": 1,
            "responsive": 1,
            "retail": 1,
            "retailers": 1,
            "risk": 1,
            "risks": 1,
            "sabotage": 1,
            "science": 2,
            "scroll": 1,
            "securities": 1,
            "security": 1,
            "sell": 1,
            "senior": 1,
            "service": 1,
            "services": 8,
            "set": 1,
            "simple": 1,
            "sitemap": 1,
            "slavery": 1,
            "social": 1,
            "solutions": 2,
            "specialist": 3,
            "staff": 1,
            "statement": 1,
            "stay": 1,
            "step": 1,
            "strategic": 1,
            "studies": 2,
            "supplements": 1,
            "surgeons": 1,
            "take": 1,
            "team": 4,
            "technology": 6,
            "terms": 1,
            "terrorism": 3,
            "that": 1,
            "the": 12,
            "throughout": 1,
            "tips": 1,
            "to": 11,
            "tools": 1,
            "top": 1,
            "touch": 1,
            "transaction": 2,
            "trusted": 3,
            "uk": 4,
            "umbrella": 1,
            "underpins": 1,
            "unrivalled": 1,
            "up": 1,
            "usa": 1,
            "use": 1,
            "value": 1,
            "very": 2,
            "warranty": 1,
            "was": 2,
            "we": 5,
            "webinars": 2,
            "were": 2,
            "wherever": 1,
            "who": 1,
            "why": 2,
            "with": 2,
            "wont": 1,
            "word": 1,
            "workplace": 1,
            "world": 1,
            "year": 1,
            "you": 1,
        }
